SRCS := adb.c fdevent.c transport.c transport_local.c transport_usb.c \
	adb_auth_client.c sockets.c services.c file_sync_service.c jdwp_service.c \
	framebuffer_service.c remount_service.c usb_linux_client.c openwrt.c \
	../libcutils/socket_inaddr_any_server.c ../libcutils/socket_local_client.c \
	../libcutils/socket_local_server.c ../libcutils/socket_loopback_client.c \
	../libcutils/socket_loopback_server.c ../libcutils/socket_network_client.c \
	../libmincrypt/rsa.c ../libmincrypt/sha.c ../libmincrypt/sha256.c

OBJS := $(addprefix .adbd/,$(SRCS:.c=.o))
# Keep daemon objects separate from the host adb objects, including libraries.
OBJS := $(subst .adbd/../,.adbd/,$(OBJS))

CPPFLAGS += -DADB_HOST=0 -DOPENWRT_ADBD -DHAVE_FORKEXEC=1 \
	-D_GNU_SOURCE -D_XOPEN_SOURCE=700 -D_FILE_OFFSET_BITS=64 \
	-DHAVE_LINUX_LOCAL_SOCKET_NAMESPACE=1 -DHAVE_SYS_SOCKET_H=1 \
	-DHAVE_SYMLINKS=1 \
	-include openwrt.h -I. -I../include

all: adbd

adbd: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) -lmbedcrypto -lpthread

.adbd/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

.adbd/libcutils/%.o: ../libcutils/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

.adbd/libmincrypt/%.o: ../libmincrypt/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<
